#!/bin/sh

# If changing jarFile or java definitions: there must not be any space
# characters either before or after the equals sign.  Important note: you must
# use *forward* slashes in the pathnames below (for jarFile and java) -- even
# if you are using win95.

# Change the value after the equals sign to the full path of the jar file.
jarFile=/home/frankg/tools/JavaDeps-1.1/jdeps.jar

# Change the value after the equals sign to the full pathname of your java
# binary, if it is not on your PATH.
java=java

# For win95, all kinds of weird things happen with make & bash if
# the directory separator is *not* a double-backslash.
if [ "$OSTYPE" = win32 ]; then
    args=`echo "$@" | sed 's,/,\\\\\\\\,g'`
else
    args="$@"
fi

if [ -z ${CLASSPATH:=""} ] ; then
    CLASSPATH=${jarFile}
else
    CLASSPATH=${jarFile}:${CLASSPATH}
fi
export CLASSPATH

exec $java smr.JavaDeps.JavaDeps $args


