#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#1b5994cc'  # default
T='#31ad69cc'  # text
W='#880000bb'  # wrong
V='#94a83bcc'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 3            \
--blur 5              \
--clock               \
--indicator           \
--time-str="%H:%M:%S"  \
--date-str="%d.%m.%Y" \
--keylayout 1         \
