#!/usr/bin/env bash

set -euo pipefail

# apt install gitlab-cli
GLAB='python-gitlab'
WORKDIR="${HOME}/work/src/mka2/lib"

all-projects() {
  for p in $($GLAB group-project list --all --group-id "$2"|sed '/^\s*$/d'|sed 's/id:\s*//'); do
  prj=$($GLAB project get --id "$p" | grep -e '^path:'|awk '{print $2}')

  if [ ! -d "./${prj}" ]; then
    echo "cloning ${1}/${prj} into $(pwd)"
    git clone "git@mka.git.syseleven.de:mka/${1}/${prj}.git"
  fi
  done
}

### main ###
which "$GLAB" >/dev/null || exit 1


# clone missing projects in /lib
cd "$WORKDIR"
all-projects "lib" 9
cd - >/dev/null

# clone missing projects in /lib/ctrl
cd "$WORKDIR/ctrl"
all-projects "lib/controllers" 12
cd - >/dev/null
