#!/bin/sh
#
# Prozessangaben anzeigen
# Aufruf: (scriptname) <prozess_id>

ps -elf >/tmp/pro$$
a=$1

if test $a -lt 0 ; then
	a=$(($a*-1))
else
	echo "PID    PPID    UID    TTY    CMD"
fi

trap "rm /tmp/pro$$; exit" 2
(
 while read n ; do
	 x=`echo $n | cut -f4 -d' '`
	 if test "$x" -eq "$a" ; then
		 p=`echo $n | cut -f4 -d' '`
		 pp=`echo $n | cut -f5 -d' '`
		 u=`echo $n | cut -f3 -d' '`
		 t=`echo $n | cut -f12 -d' '`
		 c=`echo $n | cut -f14- -d' '`
		 echo "$p    $pp    $u    $t    $c"
		 if test $pp -ne 0 ; then
			 ./$0 -$pp
		 fi
		 break
	 fi
 done
) </tmp/pro$$

rm /tmp/pro$$
