#!/bin/sh

#./q3ded +set dedicated 2 +set net_IP 172.27.40.41 +set com_hunkmegs 128 +set fs_basepath ./ +set fs_game osp +set ttycon 0 +exec server.cfg +set vm_game 2 +set vm_ui 2
#./q3ded +set dedicated 2 +set net_IP 172.27.40.41 +set com_hunkmegs 128 +set fs_basepath ./ +set fs_game osp
QUAKEDIR=/usr/local/games/quake3

sudo ${QUAKEDIR}/q3ded +set sv_pure 1 +set fs_game osp +set fs_basepath ${QUAKEDIR} +set com_hunkmegs 64  +set vm_game 2 +cvar_restart +set logfile 3 +set dedicated 1 +sets gamestartup \"`date +"%D %T"`\" +set net_port 27960 +set net_ip 172.27.40.41 +exec ${QUAKEDIR}/server.cfg +bot_enable 1 +g_gametype 1 +sv_maxclients 32 > /var/log/q3/server.log 2>&1 &
